import 'polyfill-array-includes';
import 'array-from-polyfill';
import 'custom-event-polyfill';
import objectassign from 'es6-object-assign';
import find from 'array.prototype.find';
import findIndex from 'array.prototype.findindex';
import svg4everybody from 'svg4everybody';
import picturefill from 'picturefill';
import objectFitImages from 'object-fit-images';
import './globalOptions';
import './modernizr';
import './functions/detectors';
import anchor from './functions/anchor';
import {
  freezebuttons,
} from './functions/freeze';
import positioning from './functions/position';
import scrollbar from '../blocks/scrollbar/scrollbar';
import scrollanimation from './functions/scrollanimation';
import ndSelects from '../blocks/form-elements/nd-select';
import sliders from '../blocks/form-elements/form-elements';
import textareaAutosize from '../blocks/form-elements/textareaAutosize';
import numberinput from '../blocks/form-elements/numberinputs';
import popups from '../blocks/popups/popups';
import header from '../components/header/header';
import scrollCont from '../blocks/sidebar/sidebar';
import slider from '../blocks/slider/slider';
import tooltips from '../blocks/tooltip/tooltip';
import '../blocks/put-block-into-slot/put-block-into-slot';
import heartActivation from '../blocks/button-heart/button-heart';
import offerSelect from '../blocks/offer-select/offer-select';
import floatingLabels from '../blocks/form-box/form-box';
import formManipulations from '../blocks/form/form';
import deleteObject from './functions/deleteObject';
import setBlogNewsTitlesHeight from '../blocks/blog/blog';
import '../blocks/form/validate';
import stickyMessage from '../blocks/sticky-message/sticky-message';
import blockHeightRounding from './functions/blockHeightRounding';
import '../blocks/avatar-uploader/avatar-uploader';
import uploader from '../blocks/uploader/nd-uploader';
import toggleFilter from '../components/search-filter/search-filter';
import truncateBlocks from './functions/lineClamp';
import {
  mapManipulations,
  ndSearchMapManipulations,
} from '../components/search-map/search-map';
import textareaCounters from '../blocks/form-elements/textareaCounters';
import infoNoitces from '../blocks/info-notices/info-notices';
import compositeTab from '../blocks/composite-tab/composite-tab';
import newSpaceStep6 from '../pages/new-space/new-space-step8';
import newSpaceStep5 from '../pages/new-space/new-space-step5';
import photoPreview from '../blocks/photo-preview/photo-preview';
import fileUploader from '../blocks/file-uploader/file-uploader';
import fileRemove from '../blocks/file/file';
import profile from '../pages/profile/profile';
import cancelationPopupSteps from '../components/popup-cancelation-contract/cancelationPopupSteps';
import stpFormSwitch from './functions/stepForm';
import autocompleteList from '../blocks/autocomplete-list/autocomplete-list';
import offerCard from '../components/offer-card/offer-card';
import dates from '../blocks/datepicker/datepicker';
import switchFormContent from './functions/switchFormContent';
import filterMenu from '../components/filter-menu/filter-menu';
import initCharts from '../blocks/chart/chartInit';
import buttonHover from '../blocks/button/button';
import copyToClip from './functions/copy';
import locationTagsMax from '../components/tags-map/tags-map';
import mapPopup from '../blocks/map-popup/map-popup';
import formSubmitSwitch from './functions/formSubmitSwitch';
import allDayFixation from './functions/allDayFixation';
import ndCropedImage from '../components/popup-image-cropper/popup-image-cropper';
import screenKeyboardVisibility from './functions/screenKeyboardVisibility';
import heightEqualizer from './functions/heightEqualizer';

const $ = window.$;

$(() => {
  objectassign.polyfill();
  find.shim();
  findIndex.shim();
  svg4everybody();
  picturefill();
  objectFitImages();
  anchor();
  freezebuttons();
  positioning();
  scrollbar();
  sliders();
  ndSelects();
  popups();
  header();
  slider();
  tooltips();
  numberinput();
  scrollanimation();
  scrollCont();
  heartActivation();
  offerSelect();
  floatingLabels();
  textareaAutosize();
  formManipulations();
  deleteObject();
  setBlogNewsTitlesHeight();
  stickyMessage();
  blockHeightRounding();
  uploader();
  mapManipulations();
  truncateBlocks();
  toggleFilter();
  textareaCounters();
  infoNoitces();
  compositeTab();
  newSpaceStep6();
  newSpaceStep5();
  photoPreview();
  fileRemove();
  fileUploader();
  profile();
  cancelationPopupSteps();
  stpFormSwitch();
  autocompleteList();
  offerCard();
  dates();
  switchFormContent();
  ndSearchMapManipulations();
  filterMenu();
  initCharts();
  buttonHover();
  copyToClip();
  locationTagsMax();
  mapPopup();
  formSubmitSwitch();
  allDayFixation();
  ndCropedImage();
  screenKeyboardVisibility();
  heightEqualizer();
});
